### ISSUE TITLE
Obsługa trafień 

### ISSUE THREAD

**Issue by DarkSide11** [DarkSide11/Czolgi-gra#3]
Na razie nie obsługuje trafień. Może być tak że liczy to na serwerze, ale moim zdaniem prościej byłoby żeby wysyłał to Klient. W metodzie handlecollisions (wiem że ma metoda se switchem wyglądała by ładniej ale na razie działa )wykrywa kolizje i ich rodzaj. po prostu jeżeli wykryje kolizje pocisk-czołg mógłby wysłać wiadomość do drugiego gracza i sprawa jest załatwiona

**Comment by A1R23** [comment]
Trafienia są obslugiwane. Interfejs uzytkownika wysyla informacje o trafieniu na serwer. Serwer przetwarza zgloszenie i odsyla stosowne informacje do graczy.
