### ISSUE TITLE
Liczenie żyć 

### ISSUE THREAD

**Issue by DarkSide11** [DarkSide11/Czolgi-gra#5]
Można to zrobić w klasie gra po prostu dodatkowa funkcja w update która rysuje odpowiednią liczbę kwadracików  na ekranie

**Comment by A1R23** [comment]
Zrobione.  Zycia przetwarzane sa na serwerze. W interfejsie uzytkownika rysowane sa tarcze. Kazdy gracz po 3 trafieniu przegrywa.
